# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: amecani <amecani@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/10/06 16:18:56 by amecani           #+#    #+#              #
#    Updated: 2024/04/29 16:58:14 by amecani          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

AUTHOR = albani night theme

NAME = libft.a
HFILE = libft.h

SOURCES = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
 ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c \
 ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c ft_strncmp.c \
 ft_memchr.c ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c \
 ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_putnbr_fd.c \
 ft_putendl_fd.c ft_putstr_fd.c ft_putchar_fd.c ft_striteri.c ft_strmapi.c \
 ft_itoa.c
 OBJECTS = $(SOURCES:.c=.o)

CFLAGS = -Wall -Werror -Wextra

all: $(NAME)

$(NAME): $(SOURCES) $(OBJECTS) $(HFILE)
	@ar rcs $(NAME) $(OBJECTS) $(HFILE)

clean :
	rm -f $(OBJECTS)

fclean: clean
	rm -rf $(NAME)

re: fclean all

bonus: all

#E